config/routes.rb
Rails.application.routes.draw do
  resources :likes
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  get "pages/home"
  get "about", to: "about#index"
  resources :posts do
    resources :likes
    resources :comments
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
  has_rich_text :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, only: %i[new edit create destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.comments.destroy_all
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :user_id ])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.rich_textarea :title %>
  </div>

  <% if current_user %>
  <div>
    <%= form.number_field :user_id, value: current_user.id, style: "display:none" %>
  </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like_section.html.erb
<turbo-frame id="like-section-<%= @post.id %>">
<% if @post.likes.exists?(user: current_user) %>
  <%= button_to post_like_path(@post, @post.likes.find_by(user: current_user)), method: :delete, remote: true, class: "like-button" do %>
    <i class="fas fa-heart" style="color: red;"></i>
  <% end %>
<% else %>
  <%= button_to post_likes_path(@post), method: :post, remote: true, class: "like-button" do %>
    <i class="far fa-heart" style="color: gray;"></i>
  <% end %>
<% end %>
<div>
  Likes: <%= @post.likes.count %>
</div>
</turbo-frame>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div>
    <strong></strong>
    <%= post.title %>
    
  </div>

  <div>
    <strong></strong>
    <%= post.user.user_name %>
    <%= time_tag post.updated_at %>
  </div>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>


<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" rel="stylesheet">

<%= turbo_stream_from @post %>

<%= render @post %>

<turbo-frame id="like_section-<%= @post.id %>">
  <%= render partial: "like_section", post: @post %>
</turbo-frame>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Delete Post", @post, method: :delete, class: "delete-button" %>

  <br/>
  <%= link_to "Back to Home", root_path%>
</div>

<%= render "comments/comments", post: @post %>